export const STRINGS = {
  en: {
    appName: "Expense Tracker",
    today: "TODAY",
    spent: "SPENT",
    net: "NET",
    dailyLog: "Daily Log",
    summary: "Summary",
    budgetIncome: "Budget & Income",
    settings: "Settings",
    date: "DATE",
    total: "TOTAL",
    budget: "BUDGET",
    remaining: "REMAINING",
    totalIncome: "Total Income",
    totalSpent: "Total Spent",
    netRemaining: "Net Remaining",
    budgetLeft: "Budget Left",
    unbudgeted: "Unbudgeted",
    budgetUsage: "BUDGET USAGE",
    breakdown: "BREAKDOWN BY CATEGORY",
    ofBudget: "of budget",
    noExpenses: "No expenses logged yet for",
    income: "INCOME",
    budgets: "BUDGETS",
    totalBudget: "TOTAL BUDGET",
    noCategories: "No categories. Add some in Settings.",
    noIncomeSources: "No income sources. Add some in Settings.",
    noCategoriesShort: "No categories. Click + Add.",
    noIncomeShort: "No income sources. Click + Add.",
    preferences: "PREFERENCES",
    currency: "CURRENCY",
    theme: "THEME",
    language: "LANGUAGE",
    dark: "Dark",
    light: "Light",
    categories: "CATEGORIES",
    incomeSources: "INCOME SOURCES",
    add: "+ Add",
    moveUp: "Move up",
    moveDown: "Move down",
    delete: "Delete",
    pickColor: "Pick color",
    dataBackup: "DATA & BACKUP",
    exportMonth: "Export",
    exportAll: "Export all data",
    csv: "CSV",
    backupHint: "Data is stored locally in your browser (localStorage). Clearing site data will erase your records — download a CSV backup periodically. CSVs open in Excel, Google Sheets, or any spreadsheet app.",
    clickToEdit: "Click to add/edit",
    confirmDeleteCat: (name) => `Delete "${name}"? Entries logged under this category in the current month will also be removed.`,
    confirmDeleteInc: (name) => `Delete "${name}"?`,
    noDataExport: "No data to export yet.",
    newCategory: "New Category",
    newSource: "New Source",
    prevYear: "Previous year",
    nextYear: "Next year",
    toggleTheme: "Toggle theme",
    introTitle: "👋 Welcome",
    introBody: "Set your currency and customize categories in Settings, then tap any cell below to log your first expense.",
    introCta: "Got it",
    introOpenSettings: "Open Settings",
    pickDay: "Pick a day",
    addExpense: "+ Add expense",
    cancel: "Cancel",
    save: "Save",
    dayTotal: "Day total",
    // Breakdown
    breakdown_tab: "Breakdown",
    thisMonth: "This month",
    last3Months: "Last 3 months",
    thisYear: "This year",
    allTime: "All time",
    totalSpent_period: "Total spent",
    barChartTitle: "BREAKDOWN BY CATEGORY",
    noSpending: "No spending in this period.",
    of_total: "of total",
    noDataYet: "No data yet — start logging in the Daily Log tab.",
    // Goals
    goals_tab: "Goals",
    addGoal: "+ New goal",
    editGoal: "Edit goal",
    goalName: "Goal name",
    goalNamePh: "e.g., Istanbul trip with family",
    goalDescription: "Description (optional)",
    goalDescPh: "Why this matters to you",
    targetAmount: "Target amount",
    currentSaved: "Currently saved",
    targetDate: "Target date",
    monthlyRequired: "Required per month",
    monthsLeft: "Months left",
    daysLeft: "Days left",
    progress: "Progress",
    goalsEmpty: "No goals yet. Set one to start tracking what you're saving toward.",
    goalsHint: "SMART goals = Specific, Measurable, Achievable, Relevant, Time-bound. We calculate what you need to save each month to reach your target on time.",
    achieved: "Achieved 🎉",
    overdue: "Past target date",
    saveGoal: "Save goal",
    markComplete: "Mark complete",
    reopen: "Reopen",
    confirmDeleteGoal: (name) => `Delete goal "${name}"? This cannot be undone.`,
    active: "Active",
    completed: "Completed",
    addToSaved: "Add to saved",
    pleaseFillRequired: "Please fill in name, target amount, and target date.",
    targetMustBeFuture: "Target date should be in the future.",
    months: ["January","February","March","April","May","June","July","August","September","October","November","December"],
    monthsShort: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
    locale: "en-US",
    defaultCats: {
      food: "Food", house: "House Exp.", utilities: "Utilities", transport: "Transport",
      health: "Health", hygiene: "Hygiene", mobile: "Mobile", rent: "Rent",
      education: "Education", family: "Family", entertainment: "Entertain.",
      gifts: "Gifts", charity: "Charity", unexpected: "Unexpected", clothing: "Clothing",
    },
    defaultIncome: {
      s1: "Salary 1", e1: "Bonus / Extra 1", s2: "Salary 2",
      e2: "Bonus / Extra 2", o1: "Other Income 1", o2: "Other Income 2",
    },
  },
  ru: {
    appName: "Учёт расходов",
    today: "СЕГОДНЯ",
    spent: "ПОТРАЧЕНО",
    net: "ОСТАТОК",
    dailyLog: "Дневник",
    summary: "Сводка",
    budgetIncome: "Бюджет и доход",
    settings: "Настройки",
    date: "ДАТА",
    total: "ИТОГО",
    budget: "БЮДЖЕТ",
    remaining: "ОСТАТОК",
    totalIncome: "Общий доход",
    totalSpent: "Всего потрачено",
    netRemaining: "Чистый остаток",
    budgetLeft: "Остаток бюджета",
    unbudgeted: "Без бюджета",
    budgetUsage: "ИСПОЛЬЗОВАНИЕ БЮДЖЕТА",
    breakdown: "ПО КАТЕГОРИЯМ",
    ofBudget: "от бюджета",
    noExpenses: "Расходов пока нет:",
    income: "ДОХОД",
    budgets: "БЮДЖЕТЫ",
    totalBudget: "ОБЩИЙ БЮДЖЕТ",
    noCategories: "Нет категорий. Добавьте в Настройках.",
    noIncomeSources: "Нет источников дохода. Добавьте в Настройках.",
    noCategoriesShort: "Нет категорий. Нажмите + Добавить.",
    noIncomeShort: "Нет источников дохода. Нажмите + Добавить.",
    preferences: "НАСТРОЙКИ",
    currency: "ВАЛЮТА",
    theme: "ТЕМА",
    language: "ЯЗЫК",
    dark: "Тёмная",
    light: "Светлая",
    categories: "КАТЕГОРИИ",
    incomeSources: "ИСТОЧНИКИ ДОХОДА",
    add: "+ Добавить",
    moveUp: "Вверх",
    moveDown: "Вниз",
    delete: "Удалить",
    pickColor: "Выбрать цвет",
    dataBackup: "ДАННЫЕ И БЭКАП",
    exportMonth: "Экспорт",
    exportAll: "Экспорт всех данных",
    csv: "CSV",
    backupHint: "Данные хранятся локально в браузере (localStorage). Очистка данных сайта удалит записи — периодически скачивайте CSV-бэкап. CSV открывается в Excel, Google Sheets или любом табличном редакторе.",
    clickToEdit: "Нажмите для редактирования",
    confirmDeleteCat: (name) => `Удалить «${name}»? Записи в этой категории за текущий месяц также будут удалены.`,
    confirmDeleteInc: (name) => `Удалить «${name}»?`,
    noDataExport: "Пока нет данных для экспорта.",
    newCategory: "Новая категория",
    newSource: "Новый источник",
    prevYear: "Предыдущий год",
    nextYear: "Следующий год",
    toggleTheme: "Сменить тему",
    introTitle: "👋 Добро пожаловать",
    introBody: "Выберите валюту и настройте категории в Настройках, затем нажмите на любую ячейку ниже, чтобы записать первый расход.",
    introCta: "Понятно",
    introOpenSettings: "Открыть настройки",
    pickDay: "Выберите день",
    addExpense: "+ Добавить расход",
    cancel: "Отмена",
    save: "Сохранить",
    dayTotal: "Итого за день",
    // Breakdown
    breakdown_tab: "Разбивка",
    thisMonth: "Этот месяц",
    last3Months: "Последние 3 месяца",
    thisYear: "Этот год",
    allTime: "Всё время",
    totalSpent_period: "Всего потрачено",
    barChartTitle: "РАЗБИВКА ПО КАТЕГОРИЯМ",
    noSpending: "В этом периоде расходов нет.",
    of_total: "от общего",
    noDataYet: "Пока нет данных — начните вводить во вкладке Дневник.",
    // Goals
    goals_tab: "Цели",
    addGoal: "+ Новая цель",
    editGoal: "Изменить цель",
    goalName: "Название цели",
    goalNamePh: "напр. Поездка в Стамбул с семьёй",
    goalDescription: "Описание (необязательно)",
    goalDescPh: "Почему это важно для вас",
    targetAmount: "Целевая сумма",
    currentSaved: "Накоплено сейчас",
    targetDate: "Целевая дата",
    monthlyRequired: "Нужно в месяц",
    monthsLeft: "Месяцев осталось",
    daysLeft: "Дней осталось",
    progress: "Прогресс",
    goalsEmpty: "Целей пока нет. Создайте одну, чтобы отслеживать, на что вы копите.",
    goalsHint: "SMART-цели: Конкретные, Измеримые, Достижимые, Релевантные, Ограниченные по времени. Мы посчитаем, сколько нужно откладывать каждый месяц, чтобы достичь цели в срок.",
    achieved: "Достигнуто 🎉",
    overdue: "Срок прошёл",
    saveGoal: "Сохранить цель",
    markComplete: "Отметить как выполненную",
    reopen: "Открыть снова",
    confirmDeleteGoal: (name) => `Удалить цель «${name}»? Это действие нельзя отменить.`,
    active: "Активные",
    completed: "Выполненные",
    addToSaved: "Добавить к накоплениям",
    pleaseFillRequired: "Заполните название, целевую сумму и дату.",
    targetMustBeFuture: "Целевая дата должна быть в будущем.",
    months: ["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"],
    monthsShort: ["Янв","Фев","Мар","Апр","Май","Июн","Июл","Авг","Сен","Окт","Ноя","Дек"],
    locale: "ru-RU",
    defaultCats: {
      food: "Еда", house: "Дом", utilities: "Коммунал.", transport: "Транспорт",
      health: "Здоровье", hygiene: "Гигиена", mobile: "Связь", rent: "Аренда",
      education: "Учёба", family: "Семья", entertainment: "Развлеч.",
      gifts: "Подарки", charity: "Благотв.", unexpected: "Непредвид.", clothing: "Одежда",
    },
    defaultIncome: {
      s1: "Зарплата 1", e1: "Бонус / Доп. 1", s2: "Зарплата 2",
      e2: "Бонус / Доп. 2", o1: "Другой доход 1", o2: "Другой доход 2",
    },
  },
};

export const detectLang = () => {
  try {
    const nav = navigator.language || "en";
    return nav.toLowerCase().startsWith("ru") ? "ru" : "en";
  } catch { return "en"; }
};
